f = open("result.txt", "r")
string = f.read().lower()
list = string.split("\n")
list.sort()
sorted_string = "\n\n".join(list)
print(sorted_string)
out = open("result-sorted.txt", "w")
out.write(sorted_string)
out.close()